on:
  push:
    branches: [main]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 🔨 Build Project
      run: |
        rm -rf dist
        mkdir dist
        # Copia il contenuto di src nella cartella dist
        cp -r src/* dist/

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ftp.plainasia.altervista.org
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        # Specifica la cartella remota. Per Altervista di solito è la root (./) 
        # o una sottocartella specifica. Mettere ./ aiuta l'azione a mappare i percorsi.
        server-dir: ./
        # Questa opzione forza l'upload anche se l'azione ha dubbi sullo stato del server
        dangerous-clean-slate: false
